model_name_or_path: __MODEL_ROOT__/merged_p2
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 32
loraplus_lr_ratio: 16.0
dataset_dir: __LLAMA_DATA_DIR__
dataset: data_p3_train
template: qwen2_vl
cutoff_len: 1024
max_samples: 100000
output_dir: __MODEL_ROOT__/lora_p3
logging_steps: 20
save_steps: 500
overwrite_output_dir: false
plot_loss: true
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
eval_strategy: "no"
freeze_vision_tower: true
ddp_timeout: 180000000
